#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ class TNudyCore + ;
#pragma link C++ class TNudyENDF + ;
#pragma link C++ class TNudyEndfTape + ;
#pragma link C++ class TNudyEndfMat + ;
#pragma link C++ class TNudyEndfFile + ;
#pragma link C++ class TNudyEndfSec + ;
#pragma link C++ class TNudyEndfCont + ;
#pragma link C++ class TNudyEndfRecord + ;
#pragma link C++ class TNudyEndfList + ;
#pragma link C++ class TNudyEndfTab1 + ;
#pragma link C++ class TNudyEndfTab2 + ;
#pragma link C++ class TNudyEndfINTG + ;
#pragma link C++ class TNudyElementTable + ;
#pragma link C++ class TNudyElementRN + ;
#pragma link C++ class TNudyManager + ;
#pragma link C++ class TNudyDB + ;
#pragma link C++ class TNudyLibrary + ;
#pragma link C++ class TNudySubLibrary + ;
#pragma link C++ class TVNudyModel + ;
#pragma link C++ class TNudyAlias + ;
#pragma link C++ class TNudyAliasCont + ;
#pragma link C++ class TNudyEndfSigma + ;
#pragma link C++ class TNudyEndfRecoPoint + ;
#pragma link C++ class TNudyEndfDoppler + ;
#pragma link C++ class TNudyEndfAng + ;
#pragma link C++ class TNudyEndfEnergy + ;
#pragma link C++ class TNudyEndfEnergyAng + ;
#pragma link C++ class TNudyEndfNuPh + ;
#pragma link C++ class TNudyEndfFissionYield + ;
#pragma link C++ class TNudyEndfPhYield + ;
#pragma link C++ class TNudyEndfPhProd + ;
#pragma link C++ class TNudyEndfPhAng + ;
#pragma link C++ class TNudyEndfPhEnergy + ;
#pragma link C++ class TNudySampling + ;
#pragma link C++ class TNudyElastic +;
#pragma link C++ class TNudyFission +;
#pragma link C++ class TNudyCapture +;
#pragma link C++ class TNudyInelastic +;
#pragma link C++ class TNudyEndfThermal +;
#pragma link C++ class TNudyElement +;
#pragma link C++ class ParticleA + ;
#pragma link C++ class geantphysics::DensityEffectData+;
#pragma link C++ class geantphysics::Element+;
#pragma link C++ class geantphysics::Isotope+;
#pragma link C++ class geantphysics::Material+;
#pragma link C++ class geantphysics::MaterialProperties+;
#pragma link C++ class geantphysics::NISTElementData+;
#pragma link C++ class geantphysics::NISTMaterialData+;
#endif
